name: Akashi Li
markdown: kramdown
title: George's Blog
permalink: '/blog/:title/'
favicon: './favicon.png'


theme_config: 
  appearance: "light"
  show_projects: true
  show_old_projects: true
  projects:
    title_projects: Portfolio
    title_old_projects: Old Projects
